{{ config(
    materialized='incremental',
    unique_key='player_game_key',
    incremental_strategy='delete+insert',
    on_schema_change='sync_all_columns',
    tags=['features', 'player', 'lagged', 'advanced'],
    indexes=[
        {'columns': ['player_game_key'], 'unique': True},
        {'columns': ['game_id']},
        {'columns': ['player_id']},
        {'columns': ['team_id']},
        {'columns': ['opponent_id']},
        {'columns': ['game_date']},
        {'columns': ['season_year']}
    ]
)
}}

with advanced_boxscore as (
    select
        -- Identifiers & Metadata
        player_game_key,
        game_id,
        player_id,
        player_name,
        team_id,
        opponent_id,
        game_date,
        season_year,

        -- Advanced Boxscore Stats
        est_off_rating,
        off_rating,
        est_def_rating,
        def_rating,
        est_net_rating,
        net_rating,
        ast_pct,
        ast_to_tov_ratio,
        ast_ratio,
        off_reb_pct,
        def_reb_pct,
        reb_pct,
        tov_ratio,
        eff_fg_pct,
        ts_pct,
        usage_pct,
        est_usage_pct,
        est_pace,
        pace,
        pace_per_40,
        possessions,
        pie,

        -- Timestamps for Incremental
        updated_at

    from {{ ref('int_player__combined_boxscore') }}
    -- Filter based on the starting year extracted from season_year
    where cast(substring(season_year from 1 for 4) as integer) >= cast(substring('{{ var('training_start_season_year') }}' from 1 for 4) as integer)
    {% if is_incremental() %}
    -- Look back a fixed number of days to ensure rolling calculations are correct near the incremental boundary.
    -- This window should be large enough to capture the game history needed for the longest rolling window (7 games).
    and game_date >= (
        select max(game_date) - interval '30 days' -- Adjusted interval for 7 games
        from {{ this }}
    )
    {% endif %}
),

final as (
    select
        -- Identifiers & Metadata
        player_game_key,
        game_id,
        player_id,
        player_name,
        team_id,
        opponent_id,
        game_date,
        season_year,

        -- Advanced Boxscore Stats - Lagged (1, 3, 5, 7 games ago)
        lag(est_off_rating, 1) over (partition by player_id order by game_date) as est_off_rating_prev_1_game,
        lag(off_rating, 1) over (partition by player_id order by game_date) as off_rating_prev_1_game,
        lag(est_def_rating, 1) over (partition by player_id order by game_date) as est_def_rating_prev_1_game,
        lag(def_rating, 1) over (partition by player_id order by game_date) as def_rating_prev_1_game,
        lag(est_net_rating, 1) over (partition by player_id order by game_date) as est_net_rating_prev_1_game,
        lag(net_rating, 1) over (partition by player_id order by game_date) as net_rating_prev_1_game,
        lag(ast_pct, 1) over (partition by player_id order by game_date) as ast_pct_prev_1_game,
        lag(ast_to_tov_ratio, 1) over (partition by player_id order by game_date) as ast_to_tov_ratio_prev_1_game,
        lag(ast_ratio, 1) over (partition by player_id order by game_date) as ast_ratio_prev_1_game,
        lag(off_reb_pct, 1) over (partition by player_id order by game_date) as off_reb_pct_prev_1_game,
        lag(def_reb_pct, 1) over (partition by player_id order by game_date) as def_reb_pct_prev_1_game,
        lag(reb_pct, 1) over (partition by player_id order by game_date) as reb_pct_prev_1_game,
        lag(tov_ratio, 1) over (partition by player_id order by game_date) as tov_ratio_prev_1_game,
        lag(eff_fg_pct, 1) over (partition by player_id order by game_date) as eff_fg_pct_prev_1_game,
        lag(ts_pct, 1) over (partition by player_id order by game_date) as ts_pct_prev_1_game,
        lag(usage_pct, 1) over (partition by player_id order by game_date) as usage_pct_prev_1_game,
        lag(est_usage_pct, 1) over (partition by player_id order by game_date) as est_usage_pct_prev_1_game,
        lag(est_pace, 1) over (partition by player_id order by game_date) as est_pace_prev_1_game,
        lag(pace, 1) over (partition by player_id order by game_date) as pace_prev_1_game,
        lag(pace_per_40, 1) over (partition by player_id order by game_date) as pace_per_40_prev_1_game,
        lag(possessions, 1) over (partition by player_id order by game_date) as possessions_prev_1_game,
        lag(pie, 1) over (partition by player_id order by game_date) as pie_prev_1_game,

        lag(est_off_rating, 3) over (partition by player_id order by game_date) as est_off_rating_prev_3_game,
        lag(off_rating, 3) over (partition by player_id order by game_date) as off_rating_prev_3_game,
        lag(est_def_rating, 3) over (partition by player_id order by game_date) as est_def_rating_prev_3_game,
        lag(def_rating, 3) over (partition by player_id order by game_date) as def_rating_prev_3_game,
        lag(est_net_rating, 3) over (partition by player_id order by game_date) as est_net_rating_prev_3_game,
        lag(net_rating, 3) over (partition by player_id order by game_date) as net_rating_prev_3_game,
        lag(ast_pct, 3) over (partition by player_id order by game_date) as ast_pct_prev_3_game,
        lag(ast_to_tov_ratio, 3) over (partition by player_id order by game_date) as ast_to_tov_ratio_prev_3_game,
        lag(ast_ratio, 3) over (partition by player_id order by game_date) as ast_ratio_prev_3_game,
        lag(off_reb_pct, 3) over (partition by player_id order by game_date) as off_reb_pct_prev_3_game,
        lag(def_reb_pct, 3) over (partition by player_id order by game_date) as def_reb_pct_prev_3_game,
        lag(reb_pct, 3) over (partition by player_id order by game_date) as reb_pct_prev_3_game,
        lag(tov_ratio, 3) over (partition by player_id order by game_date) as tov_ratio_prev_3_game,
        lag(eff_fg_pct, 3) over (partition by player_id order by game_date) as eff_fg_pct_prev_3_game,
        lag(ts_pct, 3) over (partition by player_id order by game_date) as ts_pct_prev_3_game,
        lag(usage_pct, 3) over (partition by player_id order by game_date) as usage_pct_prev_3_game,
        lag(est_usage_pct, 3) over (partition by player_id order by game_date) as est_usage_pct_prev_3_game,
        lag(est_pace, 3) over (partition by player_id order by game_date) as est_pace_prev_3_game,
        lag(pace, 3) over (partition by player_id order by game_date) as pace_prev_3_game,
        lag(pace_per_40, 3) over (partition by player_id order by game_date) as pace_per_40_prev_3_game,
        lag(possessions, 3) over (partition by player_id order by game_date) as possessions_prev_3_game,
        lag(pie, 3) over (partition by player_id order by game_date) as pie_prev_3_game,

        lag(est_off_rating, 5) over (partition by player_id order by game_date) as est_off_rating_prev_5_game,
        lag(off_rating, 5) over (partition by player_id order by game_date) as off_rating_prev_5_game,
        lag(est_def_rating, 5) over (partition by player_id order by game_date) as est_def_rating_prev_5_game,
        lag(def_rating, 5) over (partition by player_id order by game_date) as def_rating_prev_5_game,
        lag(est_net_rating, 5) over (partition by player_id order by game_date) as est_net_rating_prev_5_game,
        lag(net_rating, 5) over (partition by player_id order by game_date) as net_rating_prev_5_game,
        lag(ast_pct, 5) over (partition by player_id order by game_date) as ast_pct_prev_5_game,
        lag(ast_to_tov_ratio, 5) over (partition by player_id order by game_date) as ast_to_tov_ratio_prev_5_game,
        lag(ast_ratio, 5) over (partition by player_id order by game_date) as ast_ratio_prev_5_game,
        lag(off_reb_pct, 5) over (partition by player_id order by game_date) as off_reb_pct_prev_5_game,
        lag(def_reb_pct, 5) over (partition by player_id order by game_date) as def_reb_pct_prev_5_game,
        lag(reb_pct, 5) over (partition by player_id order by game_date) as reb_pct_prev_5_game,
        lag(tov_ratio, 5) over (partition by player_id order by game_date) as tov_ratio_prev_5_game,
        lag(eff_fg_pct, 5) over (partition by player_id order by game_date) as eff_fg_pct_prev_5_game,
        lag(ts_pct, 5) over (partition by player_id order by game_date) as ts_pct_prev_5_game,
        lag(usage_pct, 5) over (partition by player_id order by game_date) as usage_pct_prev_5_game,
        lag(est_usage_pct, 5) over (partition by player_id order by game_date) as est_usage_pct_prev_5_game,
        lag(est_pace, 5) over (partition by player_id order by game_date) as est_pace_prev_5_game,
        lag(pace, 5) over (partition by player_id order by game_date) as pace_prev_5_game,
        lag(pace_per_40, 5) over (partition by player_id order by game_date) as pace_per_40_prev_5_game,
        lag(possessions, 5) over (partition by player_id order by game_date) as possessions_prev_5_game,
        lag(pie, 5) over (partition by player_id order by game_date) as pie_prev_5_game,

        lag(est_off_rating, 7) over (partition by player_id order by game_date) as est_off_rating_prev_7_game,
        lag(off_rating, 7) over (partition by player_id order by game_date) as off_rating_prev_7_game,
        lag(est_def_rating, 7) over (partition by player_id order by game_date) as est_def_rating_prev_7_game,
        lag(def_rating, 7) over (partition by player_id order by game_date) as def_rating_prev_7_game,
        lag(est_net_rating, 7) over (partition by player_id order by game_date) as est_net_rating_prev_7_game,
        lag(net_rating, 7) over (partition by player_id order by game_date) as net_rating_prev_7_game,
        lag(ast_pct, 7) over (partition by player_id order by game_date) as ast_pct_prev_7_game,
        lag(ast_to_tov_ratio, 7) over (partition by player_id order by game_date) as ast_to_tov_ratio_prev_7_game,
        lag(ast_ratio, 7) over (partition by player_id order by game_date) as ast_ratio_prev_7_game,
        lag(off_reb_pct, 7) over (partition by player_id order by game_date) as off_reb_pct_prev_7_game,
        lag(def_reb_pct, 7) over (partition by player_id order by game_date) as def_reb_pct_prev_7_game,
        lag(reb_pct, 7) over (partition by player_id order by game_date) as reb_pct_prev_7_game,
        lag(tov_ratio, 7) over (partition by player_id order by game_date) as tov_ratio_prev_7_game,
        lag(eff_fg_pct, 7) over (partition by player_id order by game_date) as eff_fg_pct_prev_7_game,
        lag(ts_pct, 7) over (partition by player_id order by game_date) as ts_pct_prev_7_game,
        lag(usage_pct, 7) over (partition by player_id order by game_date) as usage_pct_prev_7_game,
        lag(est_usage_pct, 7) over (partition by player_id order by game_date) as est_usage_pct_prev_7_game,
        lag(est_pace, 7) over (partition by player_id order by game_date) as est_pace_prev_7_game,
        lag(pace, 7) over (partition by player_id order by game_date) as pace_prev_7_game,
        lag(pace_per_40, 7) over (partition by player_id order by game_date) as pace_per_40_prev_7_game,
        lag(possessions, 7) over (partition by player_id order by game_date) as possessions_prev_7_game,
        lag(pie, 7) over (partition by player_id order by game_date) as pie_prev_7_game,

        -- Advanced Boxscore Stats - Delta (Current - Lagged)
        est_off_rating - lag(est_off_rating, 1) over (partition by player_id order by game_date) as est_off_rating_delta_last_1_game,
        off_rating - lag(off_rating, 1) over (partition by player_id order by game_date) as off_rating_delta_last_1_game,
        est_def_rating - lag(est_def_rating, 1) over (partition by player_id order by game_date) as est_def_rating_delta_last_1_game,
        def_rating - lag(def_rating, 1) over (partition by player_id order by game_date) as def_rating_delta_last_1_game,
        est_net_rating - lag(est_net_rating, 1) over (partition by player_id order by game_date) as est_net_rating_delta_last_1_game,
        net_rating - lag(net_rating, 1) over (partition by player_id order by game_date) as net_rating_delta_last_1_game,
        ast_pct - lag(ast_pct, 1) over (partition by player_id order by game_date) as ast_pct_delta_last_1_game,
        ast_to_tov_ratio - lag(ast_to_tov_ratio, 1) over (partition by player_id order by game_date) as ast_to_tov_ratio_delta_last_1_game,
        ast_ratio - lag(ast_ratio, 1) over (partition by player_id order by game_date) as ast_ratio_delta_last_1_game,
        off_reb_pct - lag(off_reb_pct, 1) over (partition by player_id order by game_date) as off_reb_pct_delta_last_1_game,
        def_reb_pct - lag(def_reb_pct, 1) over (partition by player_id order by game_date) as def_reb_pct_delta_last_1_game,
        reb_pct - lag(reb_pct, 1) over (partition by player_id order by game_date) as reb_pct_delta_last_1_game,
        tov_ratio - lag(tov_ratio, 1) over (partition by player_id order by game_date) as tov_ratio_delta_last_1_game,
        eff_fg_pct - lag(eff_fg_pct, 1) over (partition by player_id order by game_date) as eff_fg_pct_delta_last_1_game,
        ts_pct - lag(ts_pct, 1) over (partition by player_id order by game_date) as ts_pct_delta_last_1_game,
        usage_pct - lag(usage_pct, 1) over (partition by player_id order by game_date) as usage_pct_delta_last_1_game,
        est_usage_pct - lag(est_usage_pct, 1) over (partition by player_id order by game_date) as est_usage_pct_delta_last_1_game,
        est_pace - lag(est_pace, 1) over (partition by player_id order by game_date) as est_pace_delta_last_1_game,
        pace - lag(pace, 1) over (partition by player_id order by game_date) as pace_delta_last_1_game,
        pace_per_40 - lag(pace_per_40, 1) over (partition by player_id order by game_date) as pace_per_40_delta_last_1_game,
        possessions - lag(possessions, 1) over (partition by player_id order by game_date) as possessions_delta_last_1_game,
        pie - lag(pie, 1) over (partition by player_id order by game_date) as pie_delta_last_1_game,

        est_off_rating - lag(est_off_rating, 3) over (partition by player_id order by game_date) as est_off_rating_delta_last_3_games,
        off_rating - lag(off_rating, 3) over (partition by player_id order by game_date) as off_rating_delta_last_3_games,
        est_def_rating - lag(est_def_rating, 3) over (partition by player_id order by game_date) as est_def_rating_delta_last_3_games,
        def_rating - lag(def_rating, 3) over (partition by player_id order by game_date) as def_rating_delta_last_3_games,
        est_net_rating - lag(est_net_rating, 3) over (partition by player_id order by game_date) as est_net_rating_delta_last_3_games,
        net_rating - lag(net_rating, 3) over (partition by player_id order by game_date) as net_rating_delta_last_3_games,
        ast_pct - lag(ast_pct, 3) over (partition by player_id order by game_date) as ast_pct_delta_last_3_games,
        ast_to_tov_ratio - lag(ast_to_tov_ratio, 3) over (partition by player_id order by game_date) as ast_to_tov_ratio_delta_last_3_games,
        ast_ratio - lag(ast_ratio, 3) over (partition by player_id order by game_date) as ast_ratio_delta_last_3_games,
        off_reb_pct - lag(off_reb_pct, 3) over (partition by player_id order by game_date) as off_reb_pct_delta_last_3_games,
        def_reb_pct - lag(def_reb_pct, 3) over (partition by player_id order by game_date) as def_reb_pct_delta_last_3_games,
        reb_pct - lag(reb_pct, 3) over (partition by player_id order by game_date) as reb_pct_delta_last_3_games,
        tov_ratio - lag(tov_ratio, 3) over (partition by player_id order by game_date) as tov_ratio_delta_last_3_games,
        eff_fg_pct - lag(eff_fg_pct, 3) over (partition by player_id order by game_date) as eff_fg_pct_delta_last_3_games,
        ts_pct - lag(ts_pct, 3) over (partition by player_id order by game_date) as ts_pct_delta_last_3_games,
        usage_pct - lag(usage_pct, 3) over (partition by player_id order by game_date) as usage_pct_delta_last_3_games,
        est_usage_pct - lag(est_usage_pct, 3) over (partition by player_id order by game_date) as est_usage_pct_delta_last_3_games,
        est_pace - lag(est_pace, 3) over (partition by player_id order by game_date) as est_pace_delta_last_3_games,
        pace - lag(pace, 3) over (partition by player_id order by game_date) as pace_delta_last_3_games,
        pace_per_40 - lag(pace_per_40, 3) over (partition by player_id order by game_date) as pace_per_40_delta_last_3_games,
        possessions - lag(possessions, 3) over (partition by player_id order by game_date) as possessions_delta_last_3_games,
        pie - lag(pie, 3) over (partition by player_id order by game_date) as pie_delta_last_3_games,

        est_off_rating - lag(est_off_rating, 5) over (partition by player_id order by game_date) as est_off_rating_delta_last_5_games,
        off_rating - lag(off_rating, 5) over (partition by player_id order by game_date) as off_rating_delta_last_5_games,
        est_def_rating - lag(est_def_rating, 5) over (partition by player_id order by game_date) as est_def_rating_delta_last_5_games,
        def_rating - lag(def_rating, 5) over (partition by player_id order by game_date) as def_rating_delta_last_5_games,
        est_net_rating - lag(est_net_rating, 5) over (partition by player_id order by game_date) as est_net_rating_delta_last_5_games,
        net_rating - lag(net_rating, 5) over (partition by player_id order by game_date) as net_rating_delta_last_5_games,
        ast_pct - lag(ast_pct, 5) over (partition by player_id order by game_date) as ast_pct_delta_last_5_games,
        ast_to_tov_ratio - lag(ast_to_tov_ratio, 5) over (partition by player_id order by game_date) as ast_to_tov_ratio_delta_last_5_games,
        ast_ratio - lag(ast_ratio, 5) over (partition by player_id order by game_date) as ast_ratio_delta_last_5_games,
        off_reb_pct - lag(off_reb_pct, 5) over (partition by player_id order by game_date) as off_reb_pct_delta_last_5_games,
        def_reb_pct - lag(def_reb_pct, 5) over (partition by player_id order by game_date) as def_reb_pct_delta_last_5_games,
        reb_pct - lag(reb_pct, 5) over (partition by player_id order by game_date) as reb_pct_delta_last_5_games,
        tov_ratio - lag(tov_ratio, 5) over (partition by player_id order by game_date) as tov_ratio_delta_last_5_games,
        eff_fg_pct - lag(eff_fg_pct, 5) over (partition by player_id order by game_date) as eff_fg_pct_delta_last_5_games,
        ts_pct - lag(ts_pct, 5) over (partition by player_id order by game_date) as ts_pct_delta_last_5_games,
        usage_pct - lag(usage_pct, 5) over (partition by player_id order by game_date) as usage_pct_delta_last_5_games,
        est_usage_pct - lag(est_usage_pct, 5) over (partition by player_id order by game_date) as est_usage_pct_delta_last_5_games,
        est_pace - lag(est_pace, 5) over (partition by player_id order by game_date) as est_pace_delta_last_5_games,
        pace - lag(pace, 5) over (partition by player_id order by game_date) as pace_delta_last_5_games,
        pace_per_40 - lag(pace_per_40, 5) over (partition by player_id order by game_date) as pace_per_40_delta_last_5_games,
        possessions - lag(possessions, 5) over (partition by player_id order by game_date) as possessions_delta_last_5_games,
        pie - lag(pie, 5) over (partition by player_id order by game_date) as pie_delta_last_5_games,

        est_off_rating - lag(est_off_rating, 7) over (partition by player_id order by game_date) as est_off_rating_delta_last_7_games,
        off_rating - lag(off_rating, 7) over (partition by player_id order by game_date) as off_rating_delta_last_7_games,
        est_def_rating - lag(est_def_rating, 7) over (partition by player_id order by game_date) as est_def_rating_delta_last_7_games,
        def_rating - lag(def_rating, 7) over (partition by player_id order by game_date) as def_rating_delta_last_7_games,
        est_net_rating - lag(est_net_rating, 7) over (partition by player_id order by game_date) as est_net_rating_delta_last_7_games,
        net_rating - lag(net_rating, 7) over (partition by player_id order by game_date) as net_rating_delta_last_7_games,
        ast_pct - lag(ast_pct, 7) over (partition by player_id order by game_date) as ast_pct_delta_last_7_games,
        ast_to_tov_ratio - lag(ast_to_tov_ratio, 7) over (partition by player_id order by game_date) as ast_to_tov_ratio_delta_last_7_games,
        ast_ratio - lag(ast_ratio, 7) over (partition by player_id order by game_date) as ast_ratio_delta_last_7_games,
        off_reb_pct - lag(off_reb_pct, 7) over (partition by player_id order by game_date) as off_reb_pct_delta_last_7_games,
        def_reb_pct - lag(def_reb_pct, 7) over (partition by player_id order by game_date) as def_reb_pct_delta_last_7_games,
        reb_pct - lag(reb_pct, 7) over (partition by player_id order by game_date) as reb_pct_delta_last_7_games,
        tov_ratio - lag(tov_ratio, 7) over (partition by player_id order by game_date) as tov_ratio_delta_last_7_games,
        eff_fg_pct - lag(eff_fg_pct, 7) over (partition by player_id order by game_date) as eff_fg_pct_delta_last_7_games,
        ts_pct - lag(ts_pct, 7) over (partition by player_id order by game_date) as ts_pct_delta_last_7_games,
        usage_pct - lag(usage_pct, 7) over (partition by player_id order by game_date) as usage_pct_delta_last_7_games,
        est_usage_pct - lag(est_usage_pct, 7) over (partition by player_id order by game_date) as est_usage_pct_delta_last_7_games,
        est_pace - lag(est_pace, 7) over (partition by player_id order by game_date) as est_pace_delta_last_7_games,
        pace - lag(pace, 7) over (partition by player_id order by game_date) as pace_delta_last_7_games,
        pace_per_40 - lag(pace_per_40, 7) over (partition by player_id order by game_date) as pace_per_40_delta_last_7_games,
        possessions - lag(possessions, 7) over (partition by player_id order by game_date) as possessions_delta_last_7_games,
        pie - lag(pie, 7) over (partition by player_id order by game_date) as pie_delta_last_7_games,

        advanced_boxscore.updated_at

    from advanced_boxscore
)

select *
from final
