# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'nba_data_app'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'nba_data_app'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory.
model-paths: ["models/"]
analysis-paths: ["analyses/"]
test-paths: ["tests/"]
seed-paths: ["data/"]
macro-paths: ["macros/"]
snapshot-paths: ["snapshots/"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"
  - "logs"

seeds:
  nba_data_app:
    feature_set_registry:
      quote_columns: true

# Time zone configuration
vars:
  dbt_date_time_zone: 'America/New_York'
  use_simple_schema_names: true
  training_start_season_year: 2017-18
  feature_recalc_window_days: 7

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  nba_data_app:

    analysis:
      +materialized: view
      +schema: analysis
      +tags: ["analysis"]

    # Core models
    core:
      +materialized: table
      +schema: core
      +tags: ["core"]

      dim__game_dates:
        +materialized: table
        +schema: core
        +tags: ["core", "dim__game_dates"]

      dim__games:
        +materialized: table
        +schema: core
        +tags: ["core", "dim__games"]

      dim__officials: 
        +materialized: table
        +schema: core
        +tags: ["core", "dim__officials"]

      dim__players:
        +materialized: table
        +schema: core
        +tags: ["core", "dim__players"] 

      dim__seasons:
        +materialized: table
        +schema: core
        +tags: ["core", "dim__seasons"] 

      dim__teams:
        +materialized: table
        +schema: core
        +tags: ["core", "dim__teams"]         
        
    # Staging models
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]
      
      betting:
        +materialized: view
        +tags: ["betting", "staging"]

      game:
        +materialized: view
        +tags: ["game", "staging"]
      
      league:
        +materialized: view
        +tags: ["league", "staging"]

      playbyplay:
        +materialized: view
        +tags: ["playbyplay", "staging"]

      player:
        +materialized: view
        +tags: ["player", "staging"]
          
      team:
        +materialized: view
        +tags: ["team", "staging"]
            
    # Intermediate models
    intermediate:
      +materialized: incremental
      +schema: intermediate
      +tags: ["intermediate"]

      betting:
        +materialized: incremental
        +tags: ["betting", "intermediate"]
      
      game:
        +materialized: incremental
        +tags: ["game", "intermediate"]

      playbyplay:
        +materialized: incremental
        +tags: ["playbyplay", "intermediate"]
    
      player:
        +materialized: incremental
        +tags: ["player", "intermediate"]

      team:
        +materialized: incremental
        +tags: ["team", "intermediate"]
        
    # Feature models
    features:
        +materialized: incremental
        +schema: features
        +tags: ["features"]

        player_game:
          +materialized: incremental
          +tags: ["player_game", "features"]

    # Training models
    training:
      +materialized: table
      +schema: training
      +tags: ["training"]
