{{ config(
    materialized='incremental',
    unique_key='team_game_key',
    incremental_strategy='delete+insert',
    tags=['features', 'pga', 'team', 'base', 'rolling', 'traditional'],
    indexes=[
        {'columns': ['team_game_key'], 'unique': True},
        {'columns': ['team_id', 'game_date']},
        {'columns': ['game_id']},
        {'columns': ['season_year']}
    ]
) }}

WITH source_boxscores AS (
    SELECT
        team_game_key,
        game_id,
        team_id,
        game_date,
        season_year,
        -- Traditional Stats
        fgm,
        fga,
        fg_pct,
        fg3m,
        fg3a,
        fg3_pct,
        ftm,
        fta,
        ft_pct,
        off_reb,
        def_reb,
        reb,
        ast,
        stl,
        blk,
        tov,
        pf,
        pts,
        plus_minus
    FROM {{ ref('int_team__combined_boxscore') }}
    {% if is_incremental() %}
    WHERE game_date > (SELECT MAX(game_date) FROM {{ this }})
    {% endif %}
)

SELECT
    team_game_key,
    game_id,
    team_id,
    game_date,
    season_year,

    -- Rolling traditional stats (Averages)
    round(({{ calculate_rolling_avg('fgm', 'team_id', 'game_date', 3) }})::numeric, 3) as fgm_roll_3g_avg,
    round(({{ calculate_rolling_avg('fgm', 'team_id', 'game_date', 5) }})::numeric, 3) as fgm_roll_5g_avg,
    round(({{ calculate_rolling_avg('fgm', 'team_id', 'game_date', 10) }})::numeric, 3) as fgm_roll_10g_avg,
    round(({{ calculate_rolling_avg('fga', 'team_id', 'game_date', 3) }})::numeric, 3) as fga_roll_3g_avg,
    round(({{ calculate_rolling_avg('fga', 'team_id', 'game_date', 5) }})::numeric, 3) as fga_roll_5g_avg,
    round(({{ calculate_rolling_avg('fga', 'team_id', 'game_date', 10) }})::numeric, 3) as fga_roll_10g_avg,
    round(({{ calculate_rolling_avg('fg_pct', 'team_id', 'game_date', 3) }})::numeric, 3) as fg_pct_roll_3g_avg,
    round(({{ calculate_rolling_avg('fg_pct', 'team_id', 'game_date', 5) }})::numeric, 3) as fg_pct_roll_5g_avg,
    round(({{ calculate_rolling_avg('fg_pct', 'team_id', 'game_date', 10) }})::numeric, 3) as fg_pct_roll_10g_avg,
    round(({{ calculate_rolling_avg('fg3m', 'team_id', 'game_date', 3) }})::numeric, 3) as fg3m_roll_3g_avg,
    round(({{ calculate_rolling_avg('fg3m', 'team_id', 'game_date', 5) }})::numeric, 3) as fg3m_roll_5g_avg,
    round(({{ calculate_rolling_avg('fg3m', 'team_id', 'game_date', 10) }})::numeric, 3) as fg3m_roll_10g_avg,
    round(({{ calculate_rolling_avg('fg3a', 'team_id', 'game_date', 3) }})::numeric, 3) as fg3a_roll_3g_avg,
    round(({{ calculate_rolling_avg('fg3a', 'team_id', 'game_date', 5) }})::numeric, 3) as fg3a_roll_5g_avg,
    round(({{ calculate_rolling_avg('fg3a', 'team_id', 'game_date', 10) }})::numeric, 3) as fg3a_roll_10g_avg,
    round(({{ calculate_rolling_avg('fg3_pct', 'team_id', 'game_date', 3) }})::numeric, 3) as fg3_pct_roll_3g_avg,
    round(({{ calculate_rolling_avg('fg3_pct', 'team_id', 'game_date', 5) }})::numeric, 3) as fg3_pct_roll_5g_avg,
    round(({{ calculate_rolling_avg('fg3_pct', 'team_id', 'game_date', 10) }})::numeric, 3) as fg3_pct_roll_10g_avg,
    round(({{ calculate_rolling_avg('ftm', 'team_id', 'game_date', 3) }})::numeric, 3) as ftm_roll_3g_avg,
    round(({{ calculate_rolling_avg('ftm', 'team_id', 'game_date', 5) }})::numeric, 3) as ftm_roll_5g_avg,
    round(({{ calculate_rolling_avg('ftm', 'team_id', 'game_date', 10) }})::numeric, 3) as ftm_roll_10g_avg,
    round(({{ calculate_rolling_avg('fta', 'team_id', 'game_date', 3) }})::numeric, 3) as fta_roll_3g_avg,
    round(({{ calculate_rolling_avg('fta', 'team_id', 'game_date', 5) }})::numeric, 3) as fta_roll_5g_avg,
    round(({{ calculate_rolling_avg('fta', 'team_id', 'game_date', 10) }})::numeric, 3) as fta_roll_10g_avg,
    round(({{ calculate_rolling_avg('ft_pct', 'team_id', 'game_date', 3) }})::numeric, 3) as ft_pct_roll_3g_avg,
    round(({{ calculate_rolling_avg('ft_pct', 'team_id', 'game_date', 5) }})::numeric, 3) as ft_pct_roll_5g_avg,
    round(({{ calculate_rolling_avg('ft_pct', 'team_id', 'game_date', 10) }})::numeric, 3) as ft_pct_roll_10g_avg,
    round(({{ calculate_rolling_avg('off_reb', 'team_id', 'game_date', 3) }})::numeric, 3) as off_reb_roll_3g_avg,
    round(({{ calculate_rolling_avg('off_reb', 'team_id', 'game_date', 5) }})::numeric, 3) as off_reb_roll_5g_avg,
    round(({{ calculate_rolling_avg('off_reb', 'team_id', 'game_date', 10) }})::numeric, 3) as off_reb_roll_10g_avg,
    round(({{ calculate_rolling_avg('def_reb', 'team_id', 'game_date', 3) }})::numeric, 3) as def_reb_roll_3g_avg,
    round(({{ calculate_rolling_avg('def_reb', 'team_id', 'game_date', 5) }})::numeric, 3) as def_reb_roll_5g_avg,
    round(({{ calculate_rolling_avg('def_reb', 'team_id', 'game_date', 10) }})::numeric, 3) as def_reb_roll_10g_avg,
    round(({{ calculate_rolling_avg('reb', 'team_id', 'game_date', 3) }})::numeric, 3) as reb_roll_3g_avg,
    round(({{ calculate_rolling_avg('reb', 'team_id', 'game_date', 5) }})::numeric, 3) as reb_roll_5g_avg,
    round(({{ calculate_rolling_avg('reb', 'team_id', 'game_date', 10) }})::numeric, 3) as reb_roll_10g_avg,
    round(({{ calculate_rolling_avg('ast', 'team_id', 'game_date', 3) }})::numeric, 3) as ast_roll_3g_avg,
    round(({{ calculate_rolling_avg('ast', 'team_id', 'game_date', 5) }})::numeric, 3) as ast_roll_5g_avg,
    round(({{ calculate_rolling_avg('ast', 'team_id', 'game_date', 10) }})::numeric, 3) as ast_roll_10g_avg,
    round(({{ calculate_rolling_avg('stl', 'team_id', 'game_date', 3) }})::numeric, 3) as stl_roll_3g_avg,
    round(({{ calculate_rolling_avg('stl', 'team_id', 'game_date', 5) }})::numeric, 3) as stl_roll_5g_avg,
    round(({{ calculate_rolling_avg('stl', 'team_id', 'game_date', 10) }})::numeric, 3) as stl_roll_10g_avg,
    round(({{ calculate_rolling_avg('blk', 'team_id', 'game_date', 3) }})::numeric, 3) as blk_roll_3g_avg,
    round(({{ calculate_rolling_avg('blk', 'team_id', 'game_date', 5) }})::numeric, 3) as blk_roll_5g_avg,
    round(({{ calculate_rolling_avg('blk', 'team_id', 'game_date', 10) }})::numeric, 3) as blk_roll_10g_avg,
    round(({{ calculate_rolling_avg('tov', 'team_id', 'game_date', 3) }})::numeric, 3) as tov_roll_3g_avg,
    round(({{ calculate_rolling_avg('tov', 'team_id', 'game_date', 5) }})::numeric, 3) as tov_roll_5g_avg,
    round(({{ calculate_rolling_avg('tov', 'team_id', 'game_date', 10) }})::numeric, 3) as tov_roll_10g_avg,
    round(({{ calculate_rolling_avg('pf', 'team_id', 'game_date', 3) }})::numeric, 3) as pf_roll_3g_avg,
    round(({{ calculate_rolling_avg('pf', 'team_id', 'game_date', 5) }})::numeric, 3) as pf_roll_5g_avg,
    round(({{ calculate_rolling_avg('pf', 'team_id', 'game_date', 10) }})::numeric, 3) as pf_roll_10g_avg,
    round(({{ calculate_rolling_avg('pts', 'team_id', 'game_date', 3) }})::numeric, 3) as pts_roll_3g_avg,
    round(({{ calculate_rolling_avg('pts', 'team_id', 'game_date', 5) }})::numeric, 3) as pts_roll_5g_avg,
    round(({{ calculate_rolling_avg('pts', 'team_id', 'game_date', 10) }})::numeric, 3) as pts_roll_10g_avg,
    round(({{ calculate_rolling_avg('plus_minus', 'team_id', 'game_date', 3) }})::numeric, 3) as plus_minus_roll_3g_avg,
    round(({{ calculate_rolling_avg('plus_minus', 'team_id', 'game_date', 5) }})::numeric, 3) as plus_minus_roll_5g_avg,
    round(({{ calculate_rolling_avg('plus_minus', 'team_id', 'game_date', 10) }})::numeric, 3) as plus_minus_roll_10g_avg,

    -- Rolling traditional stats (Standard Deviations)
    round(({{ calculate_rolling_stddev('fgm', 'team_id', 'game_date', 3) }})::numeric, 3) as fgm_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fgm', 'team_id', 'game_date', 5) }})::numeric, 3) as fgm_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fgm', 'team_id', 'game_date', 10) }})::numeric, 3) as fgm_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('fga', 'team_id', 'game_date', 3) }})::numeric, 3) as fga_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fga', 'team_id', 'game_date', 5) }})::numeric, 3) as fga_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fga', 'team_id', 'game_date', 10) }})::numeric, 3) as fga_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('fg_pct', 'team_id', 'game_date', 3) }})::numeric, 3) as fg_pct_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fg_pct', 'team_id', 'game_date', 5) }})::numeric, 3) as fg_pct_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fg_pct', 'team_id', 'game_date', 10) }})::numeric, 3) as fg_pct_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('fg3m', 'team_id', 'game_date', 3) }})::numeric, 3) as fg3m_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fg3m', 'team_id', 'game_date', 5) }})::numeric, 3) as fg3m_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fg3m', 'team_id', 'game_date', 10) }})::numeric, 3) as fg3m_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('fg3a', 'team_id', 'game_date', 3) }})::numeric, 3) as fg3a_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fg3a', 'team_id', 'game_date', 5) }})::numeric, 3) as fg3a_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fg3a', 'team_id', 'game_date', 10) }})::numeric, 3) as fg3a_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('fg3_pct', 'team_id', 'game_date', 3) }})::numeric, 3) as fg3_pct_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fg3_pct', 'team_id', 'game_date', 5) }})::numeric, 3) as fg3_pct_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fg3_pct', 'team_id', 'game_date', 10) }})::numeric, 3) as fg3_pct_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('ftm', 'team_id', 'game_date', 3) }})::numeric, 3) as ftm_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('ftm', 'team_id', 'game_date', 5) }})::numeric, 3) as ftm_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('ftm', 'team_id', 'game_date', 10) }})::numeric, 3) as ftm_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('fta', 'team_id', 'game_date', 3) }})::numeric, 3) as fta_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('fta', 'team_id', 'game_date', 5) }})::numeric, 3) as fta_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('fta', 'team_id', 'game_date', 10) }})::numeric, 3) as fta_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('ft_pct', 'team_id', 'game_date', 3) }})::numeric, 3) as ft_pct_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('ft_pct', 'team_id', 'game_date', 5) }})::numeric, 3) as ft_pct_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('ft_pct', 'team_id', 'game_date', 10) }})::numeric, 3) as ft_pct_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('off_reb', 'team_id', 'game_date', 3) }})::numeric, 3) as off_reb_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('off_reb', 'team_id', 'game_date', 5) }})::numeric, 3) as off_reb_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('off_reb', 'team_id', 'game_date', 10) }})::numeric, 3) as off_reb_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('def_reb', 'team_id', 'game_date', 3) }})::numeric, 3) as def_reb_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('def_reb', 'team_id', 'game_date', 5) }})::numeric, 3) as def_reb_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('def_reb', 'team_id', 'game_date', 10) }})::numeric, 3) as def_reb_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('reb', 'team_id', 'game_date', 3) }})::numeric, 3) as reb_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('reb', 'team_id', 'game_date', 5) }})::numeric, 3) as reb_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('reb', 'team_id', 'game_date', 10) }})::numeric, 3) as reb_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('ast', 'team_id', 'game_date', 3) }})::numeric, 3) as ast_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('ast', 'team_id', 'game_date', 5) }})::numeric, 3) as ast_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('ast', 'team_id', 'game_date', 10) }})::numeric, 3) as ast_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('stl', 'team_id', 'game_date', 3) }})::numeric, 3) as stl_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('stl', 'team_id', 'game_date', 5) }})::numeric, 3) as stl_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('stl', 'team_id', 'game_date', 10) }})::numeric, 3) as stl_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('blk', 'team_id', 'game_date', 3) }})::numeric, 3) as blk_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('blk', 'team_id', 'game_date', 5) }})::numeric, 3) as blk_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('blk', 'team_id', 'game_date', 10) }})::numeric, 3) as blk_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('tov', 'team_id', 'game_date', 3) }})::numeric, 3) as tov_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('tov', 'team_id', 'game_date', 5) }})::numeric, 3) as tov_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('tov', 'team_id', 'game_date', 10) }})::numeric, 3) as tov_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('pf', 'team_id', 'game_date', 3) }})::numeric, 3) as pf_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('pf', 'team_id', 'game_date', 5) }})::numeric, 3) as pf_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('pf', 'team_id', 'game_date', 10) }})::numeric, 3) as pf_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('pts', 'team_id', 'game_date', 3) }})::numeric, 3) as pts_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('pts', 'team_id', 'game_date', 5) }})::numeric, 3) as pts_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('pts', 'team_id', 'game_date', 10) }})::numeric, 3) as pts_roll_10g_stddev,
    round(({{ calculate_rolling_stddev('plus_minus', 'team_id', 'game_date', 3) }})::numeric, 3) as plus_minus_roll_3g_stddev,
    round(({{ calculate_rolling_stddev('plus_minus', 'team_id', 'game_date', 5) }})::numeric, 3) as plus_minus_roll_5g_stddev,
    round(({{ calculate_rolling_stddev('plus_minus', 'team_id', 'game_date', 10) }})::numeric, 3) as plus_minus_roll_10g_stddev,

    CURRENT_TIMESTAMP AS created_at,
    CURRENT_TIMESTAMP AS updated_at

FROM source_boxscores
